import { supabase } from '@/lib/supabase/client'

export const SPECIALTY_DEFAULTS: Record<
  string,
  { specialty: string; template_name: string; sections: any[] }
> = {
  dermatologia: {
    specialty: 'dermatologia',
    template_name: 'Dermatologia',
    sections: [
      {
        category: 'Pele',
        key: 'skin_phototype',
        label: 'Fototipo (Fitzpatrick)',
        type: 'select',
        options: [
          'I - Muito clara',
          'II - Clara',
          'III - Morena clara',
          'IV - Morena',
          'V - Morena escura',
          'VI - Negra',
        ],
        ai_mappable: true,
      },
      {
        category: 'Pele',
        key: 'complaint_area',
        label: 'Area de Queixa',
        type: 'multiselect',
        options: [
          'Face',
          'Couro cabeludo',
          'Pescoco',
          'Tronco anterior',
          'Tronco posterior',
          'Membros superiores',
          'Membros inferiores',
          'Maos',
          'Pes',
          'Unhas',
        ],
        ai_mappable: true,
      },
      {
        category: 'Pele',
        key: 'lesion_description',
        label: 'Descricao da Lesao',
        type: 'textarea',
        placeholder: 'Tipo, cor, tamanho, bordas, distribuicao...',
        ai_mappable: true,
      },
      {
        category: 'Classificacoes',
        key: 'acne_classification',
        label: 'Classificacao de Acne',
        type: 'select',
        options: [
          'Nao aplicavel',
          'Comedonica (Grau I)',
          'Papulopustulosa (Grau II)',
          'Nodulo-cistica (Grau III)',
          'Conglobata (Grau IV)',
        ],
        ai_mappable: true,
      },
      {
        category: 'Classificacoes',
        key: 'dermatoscopy',
        label: 'Dermatoscopia',
        type: 'textarea',
        placeholder: 'Padrao dermatoscopico observado...',
        ai_mappable: true,
      },
      {
        category: 'Procedimentos Esteticos',
        key: 'procedure_type',
        label: 'Tipo de Procedimento',
        type: 'multiselect',
        options: [
          'Toxina Botulinica',
          'Acido Hialuronico',
          'Peeling Quimico',
          'Laser',
          'Microagulhamento',
          'Bioestimulador',
          'Fio de PDO',
          'Criolipolise',
          'Outro',
        ],
        ai_mappable: true,
      },
      {
        category: 'Procedimentos Esteticos',
        key: 'product_used',
        label: 'Produto Utilizado',
        type: 'text',
        placeholder: 'Nome e fabricante',
        ai_mappable: true,
      },
      {
        category: 'Procedimentos Esteticos',
        key: 'product_lot',
        label: 'Lote do Produto',
        type: 'text',
        placeholder: 'Numero do lote',
        ai_mappable: false,
      },
      {
        category: 'Procedimentos Esteticos',
        key: 'total_units',
        label: 'Total de Unidades',
        type: 'number',
        unit: 'U',
        ai_mappable: true,
      },
      {
        category: 'Procedimentos Esteticos',
        key: 'body_map_required',
        label: 'Mapa Corporal',
        type: 'body_map',
        ai_mappable: false,
      },
      {
        category: 'Registro Fotografico',
        key: 'has_photos',
        label: 'Registro Fotografico Realizado',
        type: 'toggle',
        ai_mappable: false,
      },
      {
        category: 'Registro Fotografico',
        key: 'photo_notes',
        label: 'Observacoes das Fotos',
        type: 'textarea',
        placeholder: 'Descricao do antes e depois...',
        ai_mappable: false,
      },
    ],
  },
  psiquiatria: {
    specialty: 'psiquiatria',
    template_name: 'Psiquiatria',
    sections: [
      {
        category: 'Exame do Estado Mental',
        key: 'appearance',
        label: 'Aparencia',
        type: 'textarea',
        placeholder: 'Higiene, vestuario, postura...',
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'behavior',
        label: 'Comportamento',
        type: 'textarea',
        placeholder: 'Atitude, cooperacao, agitacao...',
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'mood_reported',
        label: 'Humor (relatado)',
        type: 'text',
        placeholder: 'Como o paciente descreve seu humor',
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'affect_observed',
        label: 'Afeto (observado)',
        type: 'select',
        options: [
          'Eutimico',
          'Deprimido',
          'Ansioso',
          'Euforico',
          'Irritavel',
          'Embotado',
          'Labil',
          'Incongruente',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'thought_process',
        label: 'Curso do Pensamento',
        type: 'select',
        options: [
          'Logico e coerente',
          'Circunstancial',
          'Tangencial',
          'Fuga de ideias',
          'Bloqueio',
          'Perseveracao',
          'Desagregado',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'thought_content',
        label: 'Conteudo do Pensamento',
        type: 'multiselect',
        options: [
          'Sem alteracoes',
          'Ideacao suicida',
          'Ideacao homicida',
          'Delirios persecutorios',
          'Delirios de grandeza',
          'Obsessoes',
          'Fobias',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'perception',
        label: 'Percepcao',
        type: 'multiselect',
        options: [
          'Sem alteracoes',
          'Alucinacoes auditivas',
          'Alucinacoes visuais',
          'Alucinacoes tateis',
          'Ilusoes',
          'Despersonalizacao',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'cognition',
        label: 'Cognicao',
        type: 'select',
        options: [
          'Preservada',
          'Leve deficit atencional',
          'Deficit de memoria recente',
          'Desorientacao temporal',
          'Nao avaliada',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'insight',
        label: 'Insight',
        type: 'select',
        options: ['Presente', 'Parcial', 'Ausente'],
        ai_mappable: true,
      },
      {
        category: 'Exame do Estado Mental',
        key: 'judgment',
        label: 'Julgamento e Critica',
        type: 'select',
        options: ['Preservado', 'Parcialmente comprometido', 'Comprometido'],
        ai_mappable: true,
      },
      {
        category: 'Escalas',
        key: 'phq9_score',
        label: 'PHQ-9 (Depressao)',
        type: 'number',
        min: 0,
        max: 27,
        unit: 'pontos',
        ai_mappable: false,
      },
      {
        category: 'Escalas',
        key: 'gad7_score',
        label: 'GAD-7 (Ansiedade)',
        type: 'number',
        min: 0,
        max: 21,
        unit: 'pontos',
        ai_mappable: false,
      },
      {
        category: 'Escalas',
        key: 'suicide_risk',
        label: 'Risco Suicida',
        type: 'select',
        options: ['Ausente', 'Baixo', 'Moderado', 'Alto', 'Muito Alto'],
        required: true,
        ai_mappable: true,
      },
      {
        category: 'Escalas',
        key: 'hetero_risk',
        label: 'Risco de Heteroagressividade',
        type: 'select',
        options: ['Ausente', 'Baixo', 'Moderado', 'Alto'],
        ai_mappable: true,
      },
      {
        category: 'Substancias',
        key: 'substance_use',
        label: 'Uso de Substancias',
        type: 'multiselect',
        options: [
          'Nenhum',
          'Alcool',
          'Tabaco',
          'Cannabis',
          'Cocaina/Crack',
          'Anfetaminas',
          'Opioides',
          'Benzodiazepinicos',
          'Outro',
        ],
        ai_mappable: true,
      },
      {
        category: 'Substancias',
        key: 'substance_details',
        label: 'Detalhes do Uso',
        type: 'textarea',
        placeholder: 'Frequencia, quantidade, tempo...',
        ai_mappable: true,
      },
      {
        category: 'Medicacao',
        key: 'current_medications',
        label: 'Medicacoes Psiquiatricas em Uso',
        type: 'textarea',
        placeholder: 'Nome, dose, tempo de uso, resposta...',
        ai_mappable: true,
      },
      {
        category: 'Medicacao',
        key: 'side_effects',
        label: 'Efeitos Colaterais',
        type: 'textarea',
        placeholder: 'Efeitos relatados...',
        ai_mappable: true,
      },
      {
        category: 'Medicacao',
        key: 'prescription_type',
        label: 'Tipo de Receita',
        type: 'select',
        options: [
          'Branca Simples',
          'Azul (B1)',
          'Amarela (A1)',
          'Receita Especial',
          'Nao aplicavel',
        ],
        ai_mappable: false,
      },
    ],
  },
  cardiologia: {
    specialty: 'cardiologia',
    template_name: 'Cardiologia',
    sections: [
      {
        category: 'Fatores de Risco',
        key: 'cv_risk_factors',
        label: 'Fatores de Risco Cardiovascular',
        type: 'multiselect',
        options: [
          'HAS',
          'Diabetes Mellitus',
          'Dislipidemia',
          'Tabagismo',
          'Sedentarismo',
          'Obesidade',
          'Historia Familiar DAC precoce',
        ],
        ai_mappable: true,
      },
      {
        category: 'ECG',
        key: 'ecg_rhythm',
        label: 'ECG - Ritmo',
        type: 'select',
        options: [
          'Sinusal',
          'Fibrilacao atrial',
          'Flutter atrial',
          'Taquicardia supraventricular',
          'Bloqueio AV 1 grau',
          'Bloqueio AV 2 grau',
          'Bloqueio AV 3 grau',
          'Outro',
        ],
        ai_mappable: true,
      },
      {
        category: 'ECG',
        key: 'ecg_hr',
        label: 'ECG - FC',
        type: 'number',
        unit: 'bpm',
        ai_mappable: true,
      },
      {
        category: 'ECG',
        key: 'ecg_st_changes',
        label: 'ECG - Alteracoes ST-T',
        type: 'textarea',
        placeholder: 'Alteracoes de ST e onda T...',
        ai_mappable: true,
      },
      {
        category: 'Ecocardiograma',
        key: 'echo_lvef',
        label: 'FEVE',
        type: 'number',
        unit: '%',
        min: 10,
        max: 80,
        ai_mappable: true,
      },
      {
        category: 'Ecocardiograma',
        key: 'echo_chambers',
        label: 'Diametros Cavitarios',
        type: 'textarea',
        placeholder: 'AE, VE, VD, Aorta...',
        ai_mappable: true,
      },
      {
        category: 'Ecocardiograma',
        key: 'echo_valves',
        label: 'Valvopatias',
        type: 'textarea',
        placeholder: 'Alteracoes valvares...',
        ai_mappable: true,
      },
      {
        category: 'Classificacao',
        key: 'nyha_class',
        label: 'NYHA (IC)',
        type: 'select',
        options: [
          'I - Sem limitacao',
          'II - Leve',
          'III - Moderada',
          'IV - Grave',
          'Nao aplicavel',
        ],
        ai_mappable: true,
      },
      {
        category: 'Classificacao',
        key: 'cardio_medications',
        label: 'Medicacoes Cardiologicas',
        type: 'textarea',
        placeholder: 'Nome, dose...',
        ai_mappable: true,
      },
    ],
  },
  endocrinologia: {
    specialty: 'endocrinologia',
    template_name: 'Endocrinologia',
    sections: [
      {
        category: 'Perfil Tireoidiano',
        key: 'tsh',
        label: 'TSH',
        type: 'number',
        unit: 'mUI/L',
        ai_mappable: true,
      },
      {
        category: 'Perfil Tireoidiano',
        key: 't4l',
        label: 'T4 Livre',
        type: 'number',
        unit: 'ng/dL',
        ai_mappable: true,
      },
      {
        category: 'Perfil Tireoidiano',
        key: 'thyroid_nodules',
        label: 'Nodulos Tireoidianos',
        type: 'textarea',
        placeholder: 'TI-RADS, PAAF...',
        ai_mappable: true,
      },
      {
        category: 'Perfil Glicemico',
        key: 'fasting_glucose',
        label: 'Glicemia de Jejum',
        type: 'number',
        unit: 'mg/dL',
        ai_mappable: true,
      },
      {
        category: 'Perfil Glicemico',
        key: 'hba1c',
        label: 'HbA1c',
        type: 'number',
        unit: '%',
        ai_mappable: true,
      },
      {
        category: 'Perfil Glicemico',
        key: 'insulin_therapy',
        label: 'Insulinoterapia',
        type: 'textarea',
        placeholder: 'Esquema basal-bolus...',
        ai_mappable: true,
      },
      {
        category: 'Perfil Lipidico',
        key: 'total_cholesterol',
        label: 'Colesterol Total',
        type: 'number',
        unit: 'mg/dL',
        ai_mappable: true,
      },
      {
        category: 'Perfil Lipidico',
        key: 'ldl',
        label: 'LDL',
        type: 'number',
        unit: 'mg/dL',
        ai_mappable: true,
      },
      {
        category: 'Perfil Lipidico',
        key: 'hdl',
        label: 'HDL',
        type: 'number',
        unit: 'mg/dL',
        ai_mappable: true,
      },
      {
        category: 'Perfil Lipidico',
        key: 'triglycerides',
        label: 'Triglicerideos',
        type: 'number',
        unit: 'mg/dL',
        ai_mappable: true,
      },
      {
        category: 'Antropometria',
        key: 'waist_circumference',
        label: 'Circunferencia Abdominal',
        type: 'number',
        unit: 'cm',
        ai_mappable: true,
      },
      {
        category: 'Antropometria',
        key: 'bmi_classification',
        label: 'Classificacao IMC',
        type: 'select',
        options: [
          'Abaixo do peso',
          'Eutrofico',
          'Sobrepeso',
          'Obesidade I',
          'Obesidade II',
          'Obesidade III',
        ],
        ai_mappable: true,
      },
    ],
  },
  ortopedia: {
    specialty: 'ortopedia',
    template_name: 'Ortopedia',
    sections: [
      {
        category: 'Localizacao',
        key: 'affected_region',
        label: 'Regiao Afetada',
        type: 'multiselect',
        options: [
          'Coluna cervical',
          'Coluna lombar',
          'Ombro D',
          'Ombro E',
          'Cotovelo D',
          'Cotovelo E',
          'Punho/Mao D',
          'Punho/Mao E',
          'Quadril D',
          'Quadril E',
          'Joelho D',
          'Joelho E',
          'Tornozelo/Pe D',
          'Tornozelo/Pe E',
        ],
        ai_mappable: true,
      },
      {
        category: 'Localizacao',
        key: 'body_map_required',
        label: 'Mapa Musculoesqueletico',
        type: 'body_map',
        ai_mappable: false,
      },
      {
        category: 'Exame Ortopedico',
        key: 'rom',
        label: 'Amplitude de Movimento (ROM)',
        type: 'textarea',
        placeholder: 'Flexao, extensao, rotacao...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ortopedico',
        key: 'muscle_strength',
        label: 'Forca Muscular (0-5)',
        type: 'textarea',
        placeholder: 'Grupo muscular e grau...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ortopedico',
        key: 'special_tests',
        label: 'Testes Especiais',
        type: 'multiselect',
        options: [
          'Lachman',
          'Gaveta Anterior',
          'Gaveta Posterior',
          'McMurray',
          'Phalen',
          'Tinel',
          'Neer',
          'Hawkins',
          'Thompson',
          'Lasegue',
          'Outro',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame Ortopedico',
        key: 'special_tests_details',
        label: 'Resultado dos Testes',
        type: 'textarea',
        placeholder: 'Resultados positivos e negativos...',
        ai_mappable: true,
      },
      {
        category: 'Imagem',
        key: 'imaging_type',
        label: 'Exame de Imagem',
        type: 'multiselect',
        options: [
          'Radiografia',
          'Tomografia',
          'Ressonancia Magnetica',
          'Ultrassonografia',
          'Nenhum',
        ],
        ai_mappable: true,
      },
      {
        category: 'Imagem',
        key: 'imaging_findings',
        label: 'Achados de Imagem',
        type: 'textarea',
        placeholder: 'Descricao dos achados...',
        ai_mappable: true,
      },
    ],
  },
  ginecologia: {
    specialty: 'ginecologia e obstetricia',
    template_name: 'Ginecologia e Obstetricia',
    sections: [
      {
        category: 'Historia Ginecologica',
        key: 'last_menstrual_period',
        label: 'DUM',
        type: 'text',
        placeholder: 'DD/MM/AAAA',
        ai_mappable: true,
      },
      {
        category: 'Historia Ginecologica',
        key: 'menstrual_cycle',
        label: 'Ciclo Menstrual',
        type: 'text',
        placeholder: 'Duracao, intervalo, fluxo...',
        ai_mappable: true,
      },
      {
        category: 'Historia Ginecologica',
        key: 'obstetric_history',
        label: 'Historia Obstetrica (G_P_A_)',
        type: 'text',
        placeholder: 'Ex: G3P2A1',
        ai_mappable: true,
      },
      {
        category: 'Historia Ginecologica',
        key: 'contraception',
        label: 'Metodo Contraceptivo',
        type: 'select',
        options: [
          'Nenhum',
          'ACO combinado',
          'Progestageno',
          'DIU cobre',
          'DIU hormonal',
          'Implante',
          'Preservativo',
          'Laqueadura',
          'Outro',
        ],
        ai_mappable: true,
      },
      {
        category: 'Exame Ginecologico',
        key: 'breast_exam',
        label: 'Exame das Mamas',
        type: 'textarea',
        placeholder: 'Inspecao, palpacao...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ginecologico',
        key: 'specular_exam',
        label: 'Exame Especular',
        type: 'textarea',
        placeholder: 'Colo uterino, corrimento...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ginecologico',
        key: 'colpocitology',
        label: 'Papanicolau',
        type: 'text',
        placeholder: 'Resultado e data',
        ai_mappable: true,
      },
    ],
  },
  oftalmologia: {
    specialty: 'oftalmologia',
    template_name: 'Oftalmologia',
    sections: [
      {
        category: 'Acuidade Visual',
        key: 'va_od_sc',
        label: 'AV OD (sem correcao)',
        type: 'text',
        placeholder: '20/...',
        ai_mappable: true,
      },
      {
        category: 'Acuidade Visual',
        key: 'va_oe_sc',
        label: 'AV OE (sem correcao)',
        type: 'text',
        placeholder: '20/...',
        ai_mappable: true,
      },
      {
        category: 'Acuidade Visual',
        key: 'va_od_cc',
        label: 'AV OD (com correcao)',
        type: 'text',
        placeholder: '20/...',
        ai_mappable: true,
      },
      {
        category: 'Acuidade Visual',
        key: 'va_oe_cc',
        label: 'AV OE (com correcao)',
        type: 'text',
        placeholder: '20/...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ocular',
        key: 'biomicroscopy',
        label: 'Biomicroscopia',
        type: 'textarea',
        placeholder: 'Cornea, conjuntiva, iris...',
        ai_mappable: true,
      },
      {
        category: 'Exame Ocular',
        key: 'tonometry_od',
        label: 'PIO OD',
        type: 'number',
        unit: 'mmHg',
        ai_mappable: true,
      },
      {
        category: 'Exame Ocular',
        key: 'tonometry_oe',
        label: 'PIO OE',
        type: 'number',
        unit: 'mmHg',
        ai_mappable: true,
      },
      {
        category: 'Exame Ocular',
        key: 'fundoscopy',
        label: 'Fundoscopia',
        type: 'textarea',
        placeholder: 'Papila, macula, vasos...',
        ai_mappable: true,
      },
    ],
  },
  pediatria: {
    specialty: 'pediatria',
    template_name: 'Pediatria',
    sections: [
      {
        category: 'Crescimento',
        key: 'weight_percentile',
        label: 'Peso (Percentil)',
        type: 'text',
        placeholder: 'Ex: P50, 10.5 kg',
        ai_mappable: true,
      },
      {
        category: 'Crescimento',
        key: 'height_percentile',
        label: 'Altura (Percentil)',
        type: 'text',
        placeholder: 'Ex: P75, 85 cm',
        ai_mappable: true,
      },
      {
        category: 'Crescimento',
        key: 'head_circumference',
        label: 'Perimetro Cefalico',
        type: 'text',
        placeholder: 'Ex: P50, 46 cm',
        ai_mappable: true,
      },
      {
        category: 'Crescimento',
        key: 'growth_assessment',
        label: 'Avaliacao do Crescimento',
        type: 'select',
        options: [
          'Adequado',
          'Baixo peso',
          'Baixa estatura',
          'Sobrepeso',
          'Obesidade',
          'Desnutricao',
        ],
        ai_mappable: true,
      },
      {
        category: 'Desenvolvimento',
        key: 'motor_milestones',
        label: 'Marcos Motores',
        type: 'textarea',
        placeholder: 'Sustento cefalico, sentar, andar...',
        ai_mappable: true,
      },
      {
        category: 'Desenvolvimento',
        key: 'language_milestones',
        label: 'Marcos de Linguagem',
        type: 'textarea',
        placeholder: 'Balbucio, palavras, frases...',
        ai_mappable: true,
      },
      {
        category: 'Desenvolvimento',
        key: 'development_assessment',
        label: 'Avaliacao do Desenvolvimento',
        type: 'select',
        options: [
          'Adequado',
          'Atraso motor',
          'Atraso de linguagem',
          'Atraso global',
          'TEA em investigacao',
        ],
        ai_mappable: true,
      },
      {
        category: 'Alimentacao',
        key: 'feeding_type',
        label: 'Alimentacao',
        type: 'select',
        options: [
          'Aleitamento materno exclusivo',
          'Aleitamento misto',
          'Formula',
          'Alimentacao complementar',
          'Dieta familiar',
        ],
        ai_mappable: true,
      },
      {
        category: 'Alimentacao',
        key: 'vaccination_status',
        label: 'Calendario Vacinal',
        type: 'select',
        options: ['Atualizado', 'Atrasado', 'Incompleto', 'Nao verificado'],
        ai_mappable: true,
      },
    ],
  },
  general: {
    specialty: 'geral',
    template_name: 'Clinica Geral',
    sections: [],
  },
}

export const specialtyTemplateService = {
  async getTemplateForSpecialty(specialty: string, tenant_id: string) {
    const { data } = await supabase
      .from('specialty_templates')
      .select('*')
      .eq('tenant_id', tenant_id)
      .eq('specialty', specialty.toLowerCase())
      .eq('is_default', true)
      .maybeSingle()

    if (data) {
      return {
        specialty: data.specialty,
        template_name: data.template_name,
        sections: (data.sections as any[]) || [],
      }
    }

    const normalizedSpecialty = specialty
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
    const defaultTemplate = Object.values(SPECIALTY_DEFAULTS).find(
      (t) => t.specialty === normalizedSpecialty || t.specialty === specialty.toLowerCase(),
    )

    return defaultTemplate || SPECIALTY_DEFAULTS.general
  },

  async saveCustomTemplate(
    tenant_id: string,
    specialty: string,
    template_name: string,
    sections: any[],
  ) {
    const { data: existing } = await supabase
      .from('specialty_templates')
      .select('id')
      .eq('tenant_id', tenant_id)
      .eq('specialty', specialty.toLowerCase())
      .maybeSingle()

    if (existing) {
      const { data, error } = await supabase
        .from('specialty_templates')
        .update({ template_name, sections, is_default: true })
        .eq('id', existing.id)
        .select()
        .single()
      if (error) throw error
      return data
    } else {
      const { data, error } = await supabase
        .from('specialty_templates')
        .insert({
          tenant_id,
          specialty: specialty.toLowerCase(),
          template_name,
          sections,
          is_default: true,
        })
        .select()
        .single()
      if (error) throw error
      return data
    }
  },

  async resetToDefault(tenant_id: string, specialty: string) {
    const { error } = await supabase
      .from('specialty_templates')
      .delete()
      .eq('tenant_id', tenant_id)
      .eq('specialty', specialty.toLowerCase())

    if (error) throw error
    return true
  },
}
